apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      service: httpd
      contents: static-files
