apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-files
  labels:
    service: httpd
    contents: static-files
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /container-volumes/A
    server: kubvol01
